version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: "Pacific/Honolulu"
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      dev-tools:
        dependency-type: development
        patterns:
          - "eslint*"
          - "htmlhint"
          - "prettier"
          - "@playwright*"
          - "@axe-core*"
          - "globals"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: "Pacific/Honolulu"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
